# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Church Info System
  description: Manage and present services and other events
  version: "0.0.1"
# the domain of the service
host: 77os3o0poc.execute-api.eu-central-1.amazonaws.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /dev
produces:
  - application/json
paths:
  /sites:
    get:
      summary: Sites for services and events
      description: xxx
      tags:
        - BasicData
      responses:
        200:
          description: An array of Sites
          schema:
            type: array
            items:
              $ref: '#/definitions/Site'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /preachers:
    get:
      summary: List of common preachers
      description: xxx
      tags:
        - BasicData
      responses:
        200:
          description: An array of Sites
          schema:
            type: array
            items:
              $ref: '#/definitions/Preacher'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /service-days:
    get:
      summary: Sundays and other potential days for a service
      description: xxx
      parameters:
        - name: start
          in: query
          description: Start date
          required: true
          type: string
        - name: end
          in: query
          description: End date
          required: true
          type: string
      tags:
        - GeneratedData
      responses:
        200:
          description: An array of Sites (ISO date format in ascending order)
          schema:
            type: array
            items:
              $ref: '#/definitions/Day'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /services:
    get:
      summary: cc
      description: xx
      tags: 
        - BusinessData
      responses:
        200:
          description: An array of services 
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Site:
    type: object
    properties:
      name:
        type: string
        description: Name of the site
      standardServiceStartTime:
        type: string
        description: 'Typical time for the service to start (format: hh:mm)'
  Preacher:
    type: object
    properties:
      name:
        type: string
        description: 'Full name of the preacher'
      initials:
        type: string
        description: 'Initial for short labels'
  Service:
    type: object
    properties:
      date:
        type: string
        description: ISO format
      startTime:
        type: string
        description: ISO format
      site:
        type: string
        description: 'Initial for short labels'
      preacher:
        type: string
        description: xx
      helper:
        type: string
        description: xx
      musician:
        type: string
        description: xx
      communion:
        type: boolean
  Day:
    type: object
    properties:
      date:
        type: string
        description: 'date in ISO format: yyyy-mm-dd'
      name:
        type: string
        description: Name of the day
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
